<table style="text-align: left;">
    <!-- Report Header Information -->
    <tr>
        <td colspan="6" style="font-size: 16px; font-weight: bold; text-align: left;">Admins List Report</td>
    </tr>
    <tr>
        <td colspan="6" style="color: #64748b; text-align: left;">List of all admins and their roles.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="5" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="5" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Applied Filters Section -->
    <tr>
        <td colspan="6" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Applied Filters</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Search:</td>
        <td colspan="5" style="text-align: left;">{{ $filters['search'] ?? 'None' }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Role:</td>
        <td colspan="5" style="text-align: left;">{{ $filters['role'] ?? 'All' }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Status:</td>
        <td colspan="5" style="text-align: left;">{{ $filters['status'] ?? 'All' }}</td>
    </tr>
    <tr></tr>

    <!-- Summary Section -->
    <tr>
        <td colspan="6" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Summary</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Admins:</td>
        <td colspan="5" style="text-align: left;">{{ $summary['total_admins'] ?? 0 }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Super Admins:</td>
        <td colspan="5" style="text-align: left;">{{ $summary['super_admins_count'] ?? 0 }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Other Admins:</td>
        <td colspan="5" style="text-align: left;">{{ $summary['admins_count'] ?? 0 }}</td>
    </tr>
    <tr></tr>

    <!-- Table Headers -->
    <tr>
        <th style="font-weight: bold; background-color: #0f172a; color: #ffffff; text-align: left; width: 25px;">Name</th>
        <th style="font-weight: bold; background-color: #0f172a; color: #ffffff; text-align: left; width: 30px;">Email</th>
        <th style="font-weight: bold; background-color: #0f172a; color: #ffffff; text-align: left; width: 20px;">Phone</th>
        <th style="font-weight: bold; background-color: #0f172a; color: #ffffff; text-align: left; width: 15px;">Role</th>
        <th style="font-weight: bold; background-color: #0f172a; color: #ffffff; text-align: left; width: 15px;">Status</th>
        <th style="font-weight: bold; background-color: #0f172a; color: #ffffff; text-align: left; width: 20px;">Created At</th>
    </tr>

    <!-- Table Data -->
    @foreach($admins as $admin)
    <tr>
        <td style="text-align: left;">{{ $admin['name'] }}</td>
        <td style="text-align: left;">{{ $admin['email'] }}</td>
        <td style="text-align: left;">{{ $admin['phone'] }}</td>
        <td style="text-align: left;">{{ $admin['role'] }}</td>
        <td style="text-align: left;">
            @if($admin['status'] == 'Active')
                <span style="color: #16a34a;">Active</span>
            @elseif($admin['status'] == 'Inactive')
                <span style="color: #d97706;">Inactive</span>
            @else
                <span style="color: #dc2626;">Deleted</span>
            @endif
        </td>
        <td style="text-align: left;">{{ $admin['created_at'] }}</td>
    </tr>
    @endforeach
</table>
