<table style="text-align: left;">
    <!-- Report Header -->
    <tr>
        <td colspan="10" style="font-size: 16px; font-weight: bold; text-align: left;">Category Detail and Product List Report</td>
    </tr>
    <tr>
        <td colspan="10" style="color: #64748b; text-align: left;">Comprehensive overview of category details and products within this category.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="9" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="9" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Category Details Section -->
    <tr>
        <td colspan="10" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Category Details</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Category Name:</td>
        <td colspan="9" style="text-align: left;">{{ $category_details['name'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Slug:</td>
        <td colspan="9" style="text-align: left;">/{{ $category_details['slug'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Status:</td>
        <td colspan="9" style="text-align: left;">{{ $category_details['status'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Description:</td>
        <td colspan="9" style="text-align: left;">{{ $category_details['description'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Created At:</td>
        <td colspan="9" style="text-align: left;">{{ $category_details['created_at'] }}</td>
    </tr>
    <tr></tr>

    <!-- Applied Filters Section -->
    <tr>
        <td colspan="10" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Product Filters Applied</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Status Filter:</td>
        <td colspan="9" style="text-align: left;">{{ $filters['status'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Search Query:</td>
        <td colspan="9" style="text-align: left;">{{ $filters['search'] }}</td>
    </tr>
    <tr></tr>

    <!-- Products Data Table Header -->
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">No</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Product Name</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">SKU</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Status</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Original Price</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Discount</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Final Price</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Current Stock</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Sold Units</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Created At</th>
        </tr>
    </thead>
    <tbody>
        @foreach($products as $index => $item)
        <tr>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $index + 1 }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['name'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['sku'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ ucfirst($item['status']) }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['original_price'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['discount_percent'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left; font-weight: bold;">{{ $item['final_price'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['stock'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['sold_units'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['created_at'] }}</td>
        </tr>
        @endforeach
    </tbody>
    <tr></tr>

    <!-- Summary Section -->
    <tr>
        <td colspan="10" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Category Products Summary</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Products:</td>
        <td colspan="9" style="text-align: left;">{{ $summary['total_products'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Current Stock:</td>
        <td colspan="9" style="text-align: left;">{{ $summary['total_stock'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Sold Units:</td>
        <td colspan="9" style="text-align: left;">{{ $summary['total_sold'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Inventory Value:</td>
        <td colspan="9" style="text-align: left;">{{ $summary['total_inventory_value'] }}</td>
    </tr>
</table>
