<table style="text-align: left;">
    <!-- Report Header Information -->
    <tr>
        <td colspan="7" style="font-size: 16px; font-weight: bold; text-align: left;">Category Report</td>
    </tr>
    <tr>
        <td colspan="7" style="color: #64748b; text-align: left;">Overview of product categories, active status, and product counts.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="6" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="6" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Applied Filters Section -->
    <tr>
        <td colspan="7" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Filters Applied:</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Search:</td>
        <td colspan="6" style="text-align: left;">{{ $filters['search'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Status:</td>
        <td colspan="6" style="text-align: left;">{{ $filters['status'] }}</td>
    </tr>

    <tr></tr>

    <!-- Category Data Columns -->
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">No</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Created Date</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Category Name</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Slug</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Description</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Status</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Products Count</th>
        </tr>
    </thead>
    <tbody>
        @foreach($categories as $index => $item)
        <tr>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $index + 1 }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['created_at_formatted'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['name'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['slug'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['description'] ?: '—' }}</td>
            @if($item['status'] === 'active')
            <td style="border: 1px solid #e2e8f0; font-weight: bold; text-align: left;">Active</td>
            @elseif($item['status'] === 'inactive')
            <td style="border: 1px solid #e2e8f0; font-weight: bold; text-align: left;">Inactive</td>
            @else
            <td style="border: 1px solid #e2e8f0; font-weight: bold; text-align: left;">Deleted</td>
            @endif
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['products_count'] }}</td>
        </tr>
        @endforeach
    </tbody>
    <tr></tr>

    <!-- Summary Section -->
    <tr>
        <td colspan="7" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Category Summary</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Categories:</td>
        <td colspan="6" style="text-align: left;">{{ $summary['total_categories'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Active Categories:</td>
        <td colspan="6" style="text-align: left;">{{ $summary['active_categories'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Inactive Categories:</td>
        <td colspan="6" style="text-align: left;">{{ $summary['inactive_categories'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Deleted Categories:</td>
        <td colspan="6" style="text-align: left;">{{ $summary['deleted_categories'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Products:</td>
        <td colspan="6" style="text-align: left;">{{ $summary['total_products'] }}</td>
    </tr>
</table>