<table style="text-align: left;">
    <!-- Report Header Information -->
    <tr>
        <td colspan="8" style="font-size: 16px; font-weight: bold; text-align: left;">Customer List Report</td>
    </tr>
    <tr>
        <td colspan="8" style="color: #64748b; text-align: left;">Analyze customer base, purchasing behavior, and activity status.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="7" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="7" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Applied Filters Section -->
    <tr>
        <td colspan="8" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Applied Filters</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Customer Filter:</td>
        <td colspan="7" style="text-align: left;">{{ $filters['customer'] ?? 'All' }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Status Filter:</td>
        <td colspan="7" style="text-align: left;">{{ $filters['status'] ?? 'All' }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Date Range:</td>
        <td colspan="7" style="text-align: left;">{{ $filters['date_range'] ?? 'All' }}</td>
    </tr>
    @if(isset($filters['search']) && $filters['search'] !== 'None' && !empty($filters['search']))
    <tr>
        <td style="font-weight: bold; text-align: left;">Search Query:</td>
        <td colspan="7" style="text-align: left;">{{ $filters['search'] }}</td>
    </tr>
    @endif
    <tr></tr>

    <!-- Customer Data Columns -->
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">No</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Registered Date</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Customer Name</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Email Address</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Phone Number</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Orders Count</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Total Spent</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Status</th>
        </tr>
    </thead>
    <tbody>
        @forelse($customers as $index => $item)
            <tr>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $index + 1 }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['created_at'] ?? $item['registered_date'] ?? 'N/A' }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['name'] ?? $item['customer'] ?? 'N/A' }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['email'] ?? 'N/A' }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['phone'] ?? 'N/A' }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['orders_count'] ?? $item['orders'] ?? 0 }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;" data-format="$#,##0.00">{{ number_format($item['total_spent'] ?? 0, 2, '.', '') }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['status'] ?? 'Active' }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="8" style="border: 1px solid #e2e8f0; text-align: left; color: #94a3b8;">No customers found.</td>
            </tr>
        @endforelse
    </tbody>
    <tr></tr>

    <!-- Summary Section -->
    <tr>
        <td colspan="8" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Customer Base Summary</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Customers:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['total_customers'] ?? count($customers) }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Active Customers:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['active_customers'] ?? 0 }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Inactive Customers:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['inactive_customers'] ?? 0 }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Deleted Customers:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['deleted_customers'] ?? 0 }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Customers with Orders:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['customers_with_orders'] ?? 0 }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Orders:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['total_orders'] ?? 0 }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Revenue Spent:</td>
        <td colspan="7" style="text-align: left;">
            @if(isset($summary['total_spent']))
                {{ $summary['total_spent'] }}
            @elseif(isset($summary['revenue']))
                ${{ number_format($summary['revenue'], 2) }}
            @else
                $0.00
            @endif
        </td>
    </tr>
</table>
