<table style="text-align: left;">
    <!-- Report Header -->
    <tr>
        <td colspan="7" style="font-size: 16px; font-weight: bold; text-align: left;">Customer Detail &amp; Activity Report</td>
    </tr>
    <tr>
        <td colspan="7" style="color: #64748b; text-align: left;">Comprehensive profile overview, address directory, and order history for {{ $customer['name'] }}.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="6" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="6" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Customer Overview Section -->
    <tr>
        <td colspan="7" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Customer Profile Overview</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Customer Name:</td>
        <td colspan="6" style="text-align: left;">{{ $customer['name'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Email Address:</td>
        <td colspan="6" style="text-align: left;">{{ $customer['email'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Phone Number:</td>
        <td colspan="6" style="text-align: left;">{{ $customer['phone'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Account Status:</td>
        <td colspan="6" style="text-align: left;">{{ $customer['status'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Joined Date:</td>
        <td colspan="6" style="text-align: left;">{{ $customer['created_at'] }}</td>
    </tr>
    <tr></tr>

    <!-- Account Performance Summary Section -->
    <tr>
        <td colspan="7" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Account Performance Summary</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Orders Count:</td>
        <td colspan="6" style="text-align: left;">{{ $summary['orders_count'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Amount Spent:</td>
        <td colspan="6" style="text-align: left;">{{ $summary['total_spent'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Average Order Value:</td>
        <td colspan="6" style="text-align: left;">{{ $summary['average_order_value'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Last Order Date:</td>
        <td colspan="6" style="text-align: left;">{{ $summary['last_order_at'] }}</td>
    </tr>
    <tr></tr>

    <!-- Addresses Directory Table Header -->
    <tr>
        <td colspan="7" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Saved Delivery Addresses</td>
    </tr>
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">No</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Label</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Recipient Name</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Phone Number</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Full Address</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Default</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Notes</th>
        </tr>
    </thead>
    <tbody>
        @forelse($addresses as $index => $addr)
        <tr>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $index + 1 }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $addr['label'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $addr['name'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $addr['phone'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $addr['full_address'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $addr['is_default'] ? 'Yes' : 'No' }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $addr['notes'] }}</td>
        </tr>
        @empty
        <tr>
            <td colspan="7" style="border: 1px solid #e2e8f0; text-align: left; color: #94a3b8;">No delivery addresses saved.</td>
        </tr>
        @endforelse
    </tbody>
    <tr></tr>

    <!-- Order History Table Header -->
    <tr>
        <td colspan="7" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Customer Orders History</td>
    </tr>
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">No</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Order #</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Date</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Status</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Payment Status</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Items Count</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Total Amount</th>
        </tr>
    </thead>
    <tbody>
        @forelse($orders as $index => $ord)
        <tr>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $index + 1 }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">#{{ $ord['order_number'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $ord['date'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $ord['status'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $ord['payment_status'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $ord['items_count'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left; font-weight: bold;">{{ $ord['total'] }}</td>
        </tr>
        @empty
        <tr>
            <td colspan="7" style="border: 1px solid #e2e8f0; text-align: left; color: #94a3b8;">No orders placed yet.</td>
        </tr>
        @endforelse
    </tbody>
</table>
