<table style="text-align: left;">
    <!-- Report Header Information -->
    <tr>
        <td colspan="8" style="font-size: 16px; font-weight: bold; text-align: left;">Inventory Report</td>
    </tr>
    <tr>
        <td colspan="8" style="color: #64748b; text-align: left;">Monitor inventory movement, stock in/out quantities, and warehouse stock levels.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="7" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="7" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Applied Filters Section -->
    <tr>
        <td colspan="8" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Filters Applied:</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Category:</td>
        <td colspan="7" style="text-align: left;">{{ $filters['category'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Product:</td>
        <td colspan="7" style="text-align: left;">{{ $filters['product'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Movement Type:</td>
        <td colspan="7" style="text-align: left;">{{ $filters['type'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Date Range:</td>
        <td colspan="7" style="text-align: left;">{{ $filters['date_range'] }}</td>
    </tr>
    @if(isset($filters['user']) && $filters['user'] !== 'All')
    <tr>
        <td style="font-weight: bold; text-align: left;">Processed By:</td>
        <td colspan="7" style="text-align: left;">{{ $filters['user'] }}</td>
    </tr>
    @endif
    <tr></tr>

    <!-- Inventory Data Columns -->
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">No</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Date</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Product Name</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">SKU</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Type</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Quantity</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Reference</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Processed By</th>
        </tr>
    </thead>
    <tbody>
        @foreach($inventory as $index => $item)
            <tr>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $index + 1 }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['date'] }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['product'] }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['sku'] }}</td>
                @if($item['type'] === 'IN')
                    <td style="border: 1px solid #e2e8f0; color: #059669; font-weight: bold; text-align: left;">
                @else
                    <td style="border: 1px solid #e2e8f0; color: #e11d48; font-weight: bold; text-align: left;">
                @endif
                    {{ $item['type'] }}
                </td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">
                    {{ $item['type'] === 'IN' ? '+' : '-' }}{{ $item['quantity'] }}
                </td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['reference'] }}</td>
                <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['processed_by'] }}</td>
            </tr>
        @endforeach
    </tbody>
    <tr></tr>

    <!-- Summary Section -->
    <tr>
        <td colspan="8" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Inventory Summary</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">In Stock Products:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['in_stock'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Low Stock Products:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['low_stock'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Out of Stock Products:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['out_of_stock'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Stock IN:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['stock_in'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Stock OUT:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['stock_out'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Net Movement:</td>
        <td colspan="7" style="text-align: left;">{{ $summary['net_movement'] }}</td>
    </tr>
</table>
