<table style="text-align: left;">
    <!-- Report Header -->
    <tr>
        <td colspan="8" style="font-size: 16px; font-weight: bold; text-align: left;">Order Detail Report</td>
    </tr>
    <tr>
        <td colspan="8" style="color: #64748b; text-align: left;">Comprehensive breakdown and itemized details for Order #{{ $order['order_number'] }}.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="7" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="7" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Order Summary Section -->
    <tr>
        <td colspan="8" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Order Overview</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Order Number:</td>
        <td colspan="7" style="text-align: left;">#{{ $order['order_number'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Order Date:</td>
        <td colspan="7" style="text-align: left;">{{ $order['created_at'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Order Status:</td>
        <td colspan="7" style="text-align: left;">{{ $order['status'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Payment Status:</td>
        <td colspan="7" style="text-align: left;">{{ $order['payment_status'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Payment Method:</td>
        <td colspan="7" style="text-align: left;">{{ $order['payment_method'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Created By:</td>
        <td colspan="7" style="text-align: left;">{{ $order['created_by'] }}</td>
    </tr>
    <tr></tr>

    <!-- Customer & Shipping Section -->
    <tr>
        <td colspan="8" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Customer &amp; Shipping Information</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Customer Name:</td>
        <td colspan="7" style="text-align: left;">{{ $order['customer_name'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Customer Email:</td>
        <td colspan="7" style="text-align: left;">{{ $order['customer_email'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Phone Number:</td>
        <td colspan="7" style="text-align: left;">{{ $order['customer_phone'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Shipping Address:</td>
        <td colspan="7" style="text-align: left;">{{ $order['shipping_address'] }}</td>
    </tr>
    <tr></tr>

    <!-- Items Table Header -->
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">No</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Product Name</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">SKU</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Category</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Unit Price</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Discount %</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Quantity</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Item Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach($items as $index => $item)
        <tr>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $index + 1 }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['product'] ?? '' }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['sku'] ?? '' }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['category'] ?? '' }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ number_format($item['full_price'] ?? 0, 2, '.', '') }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['discount'] ?? 0 }}%</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['quantity'] ?? 0 }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left; font-weight: bold;">{{ number_format($item['item_total'] ?? 0, 2, '.', '') }}</td>
        </tr>
        @endforeach
    </tbody>
    <tr></tr>

    <!-- Financial Summary Section -->
    <tr>
        <td colspan="8" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Financial Breakdown</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Items:</td>
        <td colspan="7" style="text-align: left;">{{ $order['items_count'] ?? 0 }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Subtotal:</td>
        <td colspan="7" style="text-align: left;">{{ number_format($order['subtotal'] ?? 0, 2, '.', '') }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Discount:</td>
        <td colspan="7" style="text-align: left;">{{ number_format($order['discount'] ?? 0, 2, '.', '') }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Shipping Cost:</td>
        <td colspan="7" style="text-align: left;">{{ number_format($order['shipping_cost'] ?? 0, 2, '.', '') }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Grand Total:</td>
        <td colspan="7" style="font-weight: bold; text-align: left; color: #1e293b;">{{ number_format($order['total'] ?? 0, 2, '.', '') }}</td>
    </tr>
</table>