<table style="text-align: left;">
    <!-- Report Header Information -->
    <tr>
        <td colspan="10" style="font-size: 16px; font-weight: bold; text-align: left;">Product Report</td>
    </tr>
    <tr>
        <td colspan="10" style="color: #64748b; text-align: left;">Analyze product catalog, category distribution, stock levels, and active status.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="9" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="9" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Applied Filters Section -->
    <tr>
        <td colspan="10" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Filters Applied:</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Category:</td>
        <td colspan="9" style="text-align: left;">{{ $filters['category'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Status:</td>
        <td colspan="9" style="text-align: left;">{{ $filters['status'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Product:</td>
        <td colspan="9" style="text-align: left;">{{ $filters['product'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Discount:</td>
        <td colspan="9" style="text-align: left;">{{ $filters['discount'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Stock Status:</td>
        <td colspan="9" style="text-align: left;">{{ $filters['stock_status'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Date Range:</td>
        <td colspan="9" style="text-align: left;">{{ $filters['date_range'] }}</td>
    </tr>

    <tr></tr>

    <!-- Product Data Columns -->
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">No</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Created At</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Product Name</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">SKU</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Category</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Price</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Discount</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Final Price</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Stock</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach($products as $index => $item)
        <tr>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $index + 1 }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['created_at_formatted'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['name'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['sku'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['category'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">${{ number_format($item['original_price'], 2) }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['discount_percent'] > 0 ? $item['discount_percent'] . '%' : '-' }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">${{ number_format($item['final_price'], 2) }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['current_stock'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['status'] }}</td>
        </tr>
        @endforeach
    </tbody>
    <tr></tr>

    <!-- Summary Section -->
    <tr>
        <td colspan="10" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Product Summary</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Products:</td>
        <td colspan="9" style="text-align: left;">{{ $summary['total_products'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Active Products:</td>
        <td colspan="9" style="text-align: left;">{{ $summary['active_products'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Inactive Products:</td>
        <td colspan="9" style="text-align: left;">{{ $summary['inactive_products'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Deleted Products:</td>
        <td colspan="9" style="text-align: left;">{{ $summary['deleted_products'] ?? 0 }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Low Stock Products:</td>
        <td colspan="9" style="text-align: left;">{{ $summary['low_stock'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Out of Stock Products:</td>
        <td colspan="9" style="text-align: left;">{{ $summary['out_of_stock'] }}</td>
    </tr>
</table>