<table style="text-align: left;">
    <!-- Report Header -->
    <tr>
        <td colspan="6" style="font-size: 16px; font-weight: bold; text-align: left;">Product Detail and Stock Movements Report</td>
    </tr>
    <tr>
        <td colspan="6" style="color: #64748b; text-align: left;">Comprehensive overview of product details and its stock movement history.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="5" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="5" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Product Details Section -->
    <tr>
        <td colspan="6" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Product Details</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Name:</td>
        <td colspan="5" style="text-align: left;">{{ $product_details['name'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">SKU:</td>
        <td colspan="5" style="text-align: left;">{{ $product_details['sku'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Category:</td>
        <td colspan="5" style="text-align: left;">{{ $product_details['category'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Status:</td>
        <td colspan="5" style="text-align: left;">{{ $product_details['status'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Original Price:</td>
        <td colspan="5" style="text-align: left;">{{ $product_details['original_price'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Discount:</td>
        <td colspan="5" style="text-align: left;">{{ $product_details['discount_percent'] > 0 ? $product_details['discount_percent'] . '%' : 'None' }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Final Price:</td>
        <td colspan="5" style="text-align: left;">{{ $product_details['final_price'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Current Stock:</td>
        <td colspan="5" style="text-align: left;">{{ $product_details['current_stock'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Sold Units:</td>
        <td colspan="5" style="text-align: left;">{{ $product_details['sold_units'] }}</td>
    </tr>
    <tr></tr>

    <!-- Applied Filters Section -->
    <tr>
        <td colspan="6" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Movement Filters Applied</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Movement Type:</td>
        <td colspan="5" style="text-align: left;">{{ $filters['type'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">User:</td>
        <td colspan="5" style="text-align: left;">{{ $filters['user'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Date Range:</td>
        <td colspan="5" style="text-align: left;">{{ $filters['date_range'] }}</td>
    </tr>
    <tr></tr>

    <!-- Stock Movements Data Columns -->
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">No</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Date</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Type</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Quantity</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Reference</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Processed By</th>
        </tr>
    </thead>
    <tbody>
        @foreach($movements as $index => $item)
        <tr>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $index + 1 }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['date'] }}</td>
            @if($item['type'] === 'IN')
            <td style="border: 1px solid #e2e8f0; font-weight: bold; color: #059669; text-align: left;">
                @else
            <td style="border: 1px solid #e2e8f0; font-weight: bold; color: #e11d48; text-align: left;">
                @endif
                {{ $item['type'] }}
            </td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">
                {{ $item['type'] === 'IN' ? '+' : '-' }}{{ $item['quantity'] }}
            </td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['reference'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['processed_by'] }}</td>
        </tr>
        @endforeach
    </tbody>
    <tr></tr>

    <!-- Summary Section -->
    <tr>
        <td colspan="6" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Movements Summary</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Stock IN:</td>
        <td colspan="5" style="text-align: left;">{{ $summary['stock_in'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Stock OUT:</td>
        <td colspan="5" style="text-align: left;">{{ $summary['stock_out'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Net Movement:</td>
        <td colspan="5" style="text-align: left;">{{ $summary['net_movement'] }}</td>
    </tr>
</table>