<table style="text-align: left;">
    <!-- Report Header Information -->
    <tr>
        <td colspan="12" style="font-size: 16px; font-weight: bold; text-align: left;">Sales Report</td>
    </tr>
    <tr>
        <td colspan="12" style="color: #64748b; text-align: left;">Analyze total sales volume, order performance, payment statuses, and revenue metrics.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="11" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="11" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Applied Filters Section -->
    <tr>
        <td colspan="12" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Filters Applied:</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Order:</td>
        <td colspan="11" style="text-align: left;">{{ $filters['order'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Order Status:</td>
        <td colspan="11" style="text-align: left;">{{ $filters['status'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Payment Status:</td>
        <td colspan="11" style="text-align: left;">{{ $filters['payment_status'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Payment Method:</td>
        <td colspan="11" style="text-align: left;">{{ $filters['payment_method'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Customer:</td>
        <td colspan="11" style="text-align: left;">{{ $filters['customer'] }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Province:</td>
        <td colspan="11" style="text-align: left;">{{ $filters['province'] ?? 'All' }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Date Range:</td>
        <td colspan="11" style="text-align: left;">{{ $filters['date_range'] }}</td>
    </tr>
    <tr></tr>

    <!-- Sales Data Columns -->
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">No</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Order Date</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Order Number</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Customer</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Order Status</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Payment Status</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Payment Method</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Items</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Subtotal</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Shipping Cost</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Discount</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Total Amount</th>
        </tr>
    </thead>
    <tbody>
        @foreach($orders as $index => $item)
        <tr>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $index + 1 }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['order_date'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['order_number'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['customer'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['order_status'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['payment_status'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['payment_method'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['total_items'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;" data-format="$#,##0.00">{{ number_format($item['subtotal'], 2, '.', '') }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;" data-format="$#,##0.00">{{ number_format($item['shipping_cost'], 2, '.', '') }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;" data-format="$#,##0.00">{{ number_format($item['discount'], 2, '.', '') }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;" data-format="$#,##0.00">{{ number_format($item['total_amount'], 2, '.', '') }}</td>
        </tr>
        @endforeach
    </tbody>
    <tr></tr>

    <!-- Summary Section -->
    <tr>
        <td colspan="12" style="font-weight: bold; background-color: #f1f5f9; text-align: left;">Sales Summary</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Revenue:</td>
        <td colspan="11" style="text-align: left;">${{ number_format($summary['revenue'], 2) }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Total Orders:</td>
        <td colspan="11" style="text-align: left;">{{ number_format($summary['orders']) }} orders</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Products Sold:</td>
        <td colspan="11" style="text-align: left;">{{ number_format($summary['products_sold']) }} products</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Average Order Value:</td>
        <td colspan="11" style="text-align: left;">${{ number_format($summary['average_order_value'], 2) }}</td>
    </tr>
</table>