<table style="text-align: left;">
    <!-- Report Header Information -->
    <tr>
        <td colspan="10" style="font-size: 16px; font-weight: bold; text-align: left;">Order Details</td>
    </tr>
    <tr>
        <td colspan="10" style="color: #64748b; text-align: left;">Detailed breakdown of products in each order.</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated At:</td>
        <td colspan="9" style="text-align: left;">{{ $generated_at }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: left;">Generated By:</td>
        <td colspan="9" style="text-align: left;">{{ $generated_by }}</td>
    </tr>
    <tr></tr>

    <!-- Order Details Data Columns -->
    <thead>
        <tr>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Order #</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Customer</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Product</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">SKU</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Category</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Full Price</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Discount</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Final Price</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Quantity</th>
            <th style="font-weight: bold; background-color: #e2e8f0; border: 1px solid #cbd5e1; text-align: left;">Item Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach($order_details as $item)
        <tr>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['order_number'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['customer'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['product'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['sku'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['category'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;" data-format="$#,##0.00">{{ number_format($item['full_price'], 2, '.', '') }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['discount'] }}%</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;" data-format="$#,##0.00">{{ number_format($item['final_price'], 2, '.', '') }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;">{{ $item['quantity'] }}</td>
            <td style="border: 1px solid #e2e8f0; text-align: left;" data-format="$#,##0.00">{{ number_format($item['item_total'], 2, '.', '') }}</td>
        </tr>
        @endforeach
    </tbody>
</table>